---
kind: pipeline
name: pre-checks

steps:
  - name: check-things
    image: casperlabs/node-build-u1804
    commands:
      - mkdir "/tmp/$DRONE_BUILD_NUMBER"
      - echo 'creating aaa-check-things file'
      - touch "/tmp/$DRONE_BUILD_NUMBER/aaa-check-things"
      - "ls -al /tmp/$DRONE_BUILD_NUMBER"

volumes:
  - name: tmp
    path: "/tmp"
---
kind: pipeline
name: cargo-test

steps:
- name: cargo-test-simulate
  image: casperlabs/node-build-u1804
  commands:
    - echo "creating aaa-cargo-test-simulate"
    - touch "/tmp/$DRONE_BUILD_NUMBER/aaa-cargo-test-simulate"
    - "ls -al /tmp/$DRONE_BUILD_NUMBER/"

depends_on:
  - pre-checks

volumes:
  - name: tmp
    path: "/tmp"

---
kind: pipeline
name: package

steps:
  - name: build-deb-simulate
    image: casperlabs/node-build-u1804
    commands:
      - echo 'creating aaa-build-deb-simulate'
      - touch /tmp/$DRONE_BUILD_NUMBER/aaa-build-deb-simulate
      - "ls -al /tmp/$DRONE_BUILD_NUMBERS"

depends_on:
  - pre-checks

volumes:
  - name: tmp
    path: "/tmp"

---
kind: pipeline
name: diamond-bottom

steps:
  - name: check-for-files
    image: casperlabs/node-build-u1804
    commands:
      - "ls -al /tmp/$DRONE_BUILD_NUMBERS"

depends_on:
  - package
  - cargo-test

volumes:
  - name: tmp
    path: "/tmp"

