---
kind: pipeline
name: pre-checks

steps:
- name: check-things
  image: casperlabs/node-build-u1804
  commands:
  - echo 'Pre-checking!'

---
kind: pipeline
name: cargo-test

steps:
- name: cargo-test-simulate
  image: casperlabs/node-build-u1804
  commands:
    - echo "creating aaa-cargo-test-simulate"
    - touch "aaa-cargo-test-simulate"
    - ./ci/drone_s3_storage.sh put aaa-cargo-test-simulate /test_file/aaa-cargo-test-simulate

depends_on:
  - pre-checks

---
kind: pipeline
name: package

steps:
- name: build-deb-simulate
  image: casperlabs/node-build-u1804
  commands:
  - echo "creating aaa-package-test-simulate"
  - touch "aaa-package-test-simulate"
  - ./ci/drone_s3_storage.sh put aaa-package-test-simulate /test_file/aaa-package-test-simulate

depends_on:
  - pre-checks

---
kind: pipeline
name: diamond-bottom

steps:
- name: check-for-files
  image: casperlabs/node-build-u1804
  commands:
  - ./ci/drone_s3_storage.sh get /test_file/aaa-package-test-simulate aaa-package-test-simulate
  - ./ci/drone_s3_storage.sh get /test_file/aaa-cargo-test-simulate aaa-cargo-test-simulate
  - ls -al

depends_on:
  - package
  - cargo-test
