---
kind: pipeline
name: pre-checks

steps:
- name: check-things
  image: casperlabs/s3cmd-build:latest
  commands:
  - echo 'Pre-checking!'

---
kind: pipeline
name: cargo-test

steps:
- name: cargo-test-simulate
  image: casperlabs/s3cmd-build:latest
  commands:
    - echo "testing"

depends_on:
  - pre-checks

---
kind: pipeline
name: package

steps:
- name: build-deb-simulate
  image: casperlabs/s3cmd-build:latest
  environment:
    CL_VAULT_TOKEN:
      from_secret: vault_token
    CL_VAULT_HOST:
      from_secret: vault_host
  commands:
  - echo "creating aaa-package-test-simulate"
  - touch "aaa-package-test-simulate"
  - ./ci/drone_s3_storage.sh put $(pwd)/resources/ resources/

depends_on:
  - pre-checks

---
kind: pipeline
name: diamond-bottom

steps:
- name: check-for-files
  image: casperlabs/s3cmd-build:latest
  environment:
    CL_VAULT_TOKEN:
      from_secret: vault_token
    CL_VAULT_HOST:
      from_secret: vault_host
  commands:
    - mkdir $(pwd)/dup_res
    - ./ci/drone_s3_storage.sh get resources/ $(pwd)/dup_res/
    - ./ci/drone_s3_storage.sh del
    - ls -al $(pwd)/dup_res

depends_on:
  - package
  - cargo-test
