---
kind: pipeline
name: pre-checks

steps:
  - name: check-things
    image: casperlabs/node-build-u1804
    commands:
      - echo 'creating aaa-check-things file'
      - touch aaa-check-things
---
kind: pipeline
name: cargo-test

steps:
- name: cargo-test-simulate
  image: casperlabs/node-build-u1804
  commands:
    - echo "creating aaa-cargo-test-simulate"
    - touch aaa-cargo-test-simulate

depends_on:
  - pre-checks

---
kind: pipeline
name: package

steps:
  - name: build-deb-simulate
    image: casperlabs/node-build-u1804
    commands:
      - echo 'creating aaa-build-deb-simulate'
      - touch aaa-build-deb-simulate

depends_on:
  - pre-checks

---
kind: pipeline
name: diamond-bottom

steps:
  - name: check-for-files
    image: casperlabs/node-build-u1804
    commands:
      - "ls -al"

depends_on:
  - package
  - cargo-test