[package]
name = "casper-execution-engine"
version = "0.7.0" # when updating, also update 'html_root_url' in lib.rs
authors = ["Henry Till <henrytill@gmail.com>", "Ed Hastings <ed@casperlabs.io>"]
edition = "2018"
description = "CasperLabs execution engine crates."
readme = "README.md"
documentation = "https://docs.rs/casper-execution-engine"
homepage = "https://casperlabs.io"
repository = "https://github.com/CasperLabs/casper-node/tree/master/execution_engine"
license-file = "../LICENSE"

[dependencies]
anyhow = "1.0.28"
base16 = "0.2.1"
blake2 = "0.8.1"
casper-types = { version = "0.6.0", path = "../types", features = ["std", "gens"] }
chrono = "0.4.10"
datasize = "0.2.0"
csv = "1.1.3"
hex = "0.4.2"
hex-buffer-serde = "0.2.1"
hex_fmt = "0.3.0"
hostname = "0.3.0"
itertools = "0.8.2"
lazy_static = "1.4.0"
libc = "0.2.66"
linked-hash-map = "0.5.2"
lmdb = "0.8"
log = { version = "0.4.8", features = ["std", "serde", "kv_unstable"] }
num = { version = "0.2.0", default-features = false }
num-derive = "0.3.0"
num-traits = "0.2.10"
parity-wasm = "0.41.0"
proptest = { version = "0.10.0", optional = true }
pwasm-utils = "0.12.0"
rand = "0.7.3"
rand_chacha = "0.2.2"
rmp-serde = "0.14.3"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "1.0.18"
tracing = "0.1.18"
uint = "0.8.3"
uuid = { version = "0.8.1", features = ["serde", "v4"] }
wabt = "0.10.0"
wasmi = "0.6.2"

[dev-dependencies]
assert_matches = "1.3.0"
criterion = "0.3.3"
proptest = "0.10.0"
tempfile = "3.1.0"

[features]
default = ["gens"]
gens = ["proptest"]
test-support = []
no-unstable-features = ["casper-types/no-unstable-features"]

[[bench]]
name = "trie_bench"
harness = false

[package.metadata.docs.rs]
features = ["no-unstable-features"]
