[package]
name = "auction-install"
version = "0.1.0"
authors = ["Michał Papierski <michal@casperlabs.io>"]
edition = "2018"

[[bin]]
name = "auction_install"
path = "src/main.rs"
bench = false
doctest = false
test = false

[features]
std = ["casper-contract/std", "casper-types/std"]
no-unstable-features = ["casper-contract/no-unstable-features", "casper-types/no-unstable-features"]

[dependencies]
auction = { path = "../auction" }
casper-contract = { path = "../../../contract" }
casper-types = { path = "../../../../types" }
